
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mysqlproj




test:
  <<: *default
  database: mysqlproj_test



production:
  <<: *default
  database: mysqlproj_production
  username: mysqlproj
  password: <%= ENV['MYSQLPROJ_DATABASE_PASSWORD'] %>
